### ISSUE TITLE
Upload to crates.io

### ISSUE THREAD

**Issue by jtguibas** [github/twirp-rs#43]
Would it be possible to upload twirp-rs to crates.io?

@tclem

**Comment by tclem** [comment]
It'd be awesome to have this published! I think there's a small amount of work to make this happen beyond `cargo publish` as we should probably cut and document a true release.

@patrickt any interesting in helping out here? No pressure.

In the meantime, I recommend using the package from source.

**Comment by patrickt** [comment]
It appears that GitHub user @mattstam has uploaded this to crates.io. Matt, would you mind getting in touch with me (`patrickt@github.com`) so that we can get the project maintainers as admins of that package? Right now we are unable to upload new versions.

**Comment by mattstam** [comment]
> It appears that GitHub user @mattstam has uploaded this to crates.io. Matt, would you mind getting in touch with me (`patrickt@github.com`) so that we can get the project maintainers as admins of that package? Right now we are unable to upload new versions.

FYI I believe https://crates.io/crates/twirp was the original one but appeared to be outdated which caused us to publish https://crates.io/crates/twirp-rs

added you to those crates!

**Comment by patrickt** [comment]
@mattstam Thanks very much! Appreciate the quick response.
