### ISSUE TITLE
Example is probably broken

### ISSUE THREAD

**Issue by jorendorff** [github/twirp-rs#5]
We panic if `Timings` are not present in the `Request`, and nothing in the example adds `Timings` to the `Request`.

We need some kind of test for the example. :-\

**Comment by patrickt** [comment]
Wow, great catch. Will fix. I wonder if we can do a “compileable README” thing like we do over in github.com/fused-effects/fused-effects.

**Comment by patrickt** [comment]
Also, we should probably not panic if it’s possible to hold the system in such a way that Timings don’t get into things. For some reason I thought it was auto-added.
